// scripts/generate-icons.mjs — the icon-system codegen (WP-B-4b.2-B1).
//
// Reads the curation manifest (src/icons/manifest.json), pulls each icon's
// geometry from `lucide-react` (a devDependency) via its named `__iconNode`
// export, strips the React `key`, and emits our OWN committed inline-SVG `.tsx`
// — ZERO runtime dependency on lucide. Codegen is NOT runtime re-export (which
// the no-bundle rule forbids); the emitted components stand alone.
//
// Outputs (all under src/icons/generated/, committed + drift-gated):
//   ui/<name>.tsx   — one component per canonical icon (uses the shared IconBase)
//   index.ts        — the tree-shakeable named-export hub (canonical + aliases)
//   registry.ts     — ICON_REGISTRY map + ICON_NAMES + the IconName union
//
// Modes:
//   node generate-icons.mjs           — (re)generate + prettier-format + write
//   node generate-icons.mjs --check   — regenerate + format in memory, diff vs
//                                       committed; exit 1 on any drift (CI gate)
//
// Determinism: output carries no timestamp (only the pinned lucide version in
// the header), and every file is run through prettier so committed === generated.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url)); // packages/react/scripts
const PKG = dirname(HERE); // packages/react
const ICONS_DIR = join(PKG, "src", "icons");
const GENERATED_DIR = join(ICONS_DIR, "generated");
const UI_DIR = join(GENERATED_DIR, "ui");
const MANIFEST_PATH = join(ICONS_DIR, "manifest.json");

const CHECK = process.argv.includes("--check");

/** kebab-case → PascalCase (`arrow-up-right` → `ArrowUpRight`). */
const pascal = (kebab) =>
  kebab
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

/** SVG attribute name → JSX attribute name (`stroke-width` → `strokeWidth`). */
const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// --- read inputs ----------------------------------------------------------

const lucideVersion = JSON.parse(
  readFileSync(fileURLToPath(import.meta.resolve("lucide-react/package.json")), "utf8"),
).version;

const HEADER = `// AUTO-GENERATED by scripts/generate-icons.mjs from lucide-react@${lucideVersion} (ISC). Do not edit.`;

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
const icons = manifest.icons;

// --- resolve geometry + validate aliases ----------------------------------

/** Load a lucide icon's `__iconNode` (the geometry); null if the module is an alias stub. */
async function loadIconNode(name) {
  const mod = await import(`lucide-react/dist/esm/icons/${name}.mjs`);
  return mod.__iconNode ?? null;
}

/** Read an alias stub's canonical target from `export { default } from "./<canonical>.mjs"`. */
function resolveAliasTarget(aliasName) {
  const src = readFileSync(
    fileURLToPath(import.meta.resolve(`lucide-react/dist/esm/icons/${aliasName}.mjs`)),
    "utf8",
  );
  const m = src.match(/from\s+["']\.\/([a-z0-9-]+)\.mjs["']/);
  return m ? m[1] : null;
}

const seenNames = new Set();
const seenExports = new Set();
const resolved = []; // { name, exportName, aliasName, aliasExport, geometry }

for (const entry of icons) {
  const { name, exportName: exportOverride, alias } = entry;

  if (seenNames.has(name)) throw new Error(`Duplicate icon name in manifest: ${name}`);
  seenNames.add(name);

  const geometry = await loadIconNode(name);
  if (geometry === null) {
    const canonical = resolveAliasTarget(name);
    throw new Error(
      `Manifest name "${name}" is a lucide alias stub (no __iconNode). Use the canonical name` +
        (canonical ? ` "${canonical}" instead, with alias: "${name}".` : "."),
    );
  }

  const exportName = exportOverride ?? pascal(name);
  if (seenExports.has(exportName)) throw new Error(`Duplicate export name: ${exportName}`);
  seenExports.add(exportName);

  let aliasName = null;
  let aliasExport = null;
  if (alias) {
    // Exercise + validate alias resolution: the stub must point at this canonical.
    const target = resolveAliasTarget(alias);
    if (target !== name) {
      throw new Error(
        `Alias "${alias}" resolves to "${target ?? "(unknown)"}", not the declared canonical "${name}".`,
      );
    }
    aliasName = alias;
    aliasExport = pascal(alias);
    if (seenNames.has(aliasName)) throw new Error(`Alias collides with an icon name: ${aliasName}`);
    seenNames.add(aliasName);
    if (seenExports.has(aliasExport)) throw new Error(`Duplicate export name: ${aliasExport}`);
    seenExports.add(aliasExport);
  }

  resolved.push({ name, exportName, aliasName, aliasExport, geometry });
}

// --- emit raw file bodies -------------------------------------------------

/** [tag, attrs][] → JSX children (`<circle cx="12" .../>`), React `key` stripped. */
function emitGeometry(geometry) {
  return geometry
    .map(([tag, attrs]) => {
      const parts = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${camel(k)}="${v}"`)
        .join(" ");
      return `<${tag} ${parts} />`;
    })
    .join("\n");
}

function uiFile({ name, exportName, geometry }) {
  return `${HEADER}
import { IconBase } from "../../IconBase";
import type { IconProps } from "../../icon-props";

/** \`${name}\` — generated from lucide-react@${lucideVersion} (ISC). */
export function ${exportName}(props: IconProps) {
  return (
    <IconBase {...props}>
${emitGeometry(geometry)}
    </IconBase>
  );
}
`;
}

function indexFile() {
  const lines = resolved.map((r) =>
    r.aliasExport
      ? `export { ${r.exportName}, ${r.exportName} as ${r.aliasExport} } from "./ui/${r.name}";`
      : `export { ${r.exportName} } from "./ui/${r.name}";`,
  );
  return `${HEADER}
// The tree-shakeable named-export hub: \`import { TrendingUp } from "@qball-inc/react"\`
// ships only that icon's bytes (sideEffects:false + tsup treeshake:true).
${lines.join("\n")}
`;
}

function registryFile() {
  const imports = resolved.map((r) => `import { ${r.exportName} } from "./ui/${r.name}";`);
  const allNames = resolved.flatMap((r) => (r.aliasName ? [r.name, r.aliasName] : [r.name]));
  const union = allNames.map((n) => `| "${n}"`).join("\n");
  const namesArr = allNames.map((n) => `"${n}",`).join("\n");
  const registry = resolved
    .flatMap((r) =>
      r.aliasName
        ? [`"${r.name}": ${r.exportName},`, `"${r.aliasName}": ${r.exportName},`]
        : [`"${r.name}": ${r.exportName},`],
    )
    .join("\n");
  return `${HEADER}
import type { ComponentType } from "react";
import type { IconProps } from "../icon-props";
${imports.join("\n")}

/** Every shipped icon name (canonical + aliases). A 1.0 stability contract. */
export type IconName =
${union};

/** Runtime list of every IconName — the contract surface for dynamic name use. */
export const ICON_NAMES = [
${namesArr}
] as const satisfies readonly IconName[];

/**
 * name → component for the dynamic \`<Icon name>\` registry. Intentionally retains
 * the whole set (NON-shaking); for tree-shaking use the per-icon named export.
 */
export const ICON_REGISTRY: Record<IconName, ComponentType<IconProps>> = {
${registry}
};
`;
}

// --- format -------------------------------------------------------------

const prettier = await import("prettier");

/** Build the full path → prettier-formatted content map for all generated files. */
async function buildOutputs() {
  const raw = new Map();
  for (const r of resolved) raw.set(join(UI_DIR, `${r.name}.tsx`), uiFile(r));
  raw.set(join(GENERATED_DIR, "index.ts"), indexFile());
  raw.set(join(GENERATED_DIR, "registry.ts"), registryFile());

  const out = new Map();
  for (const [path, body] of raw) {
    const cfg = await prettier.resolveConfig(path);
    out.set(path, await prettier.format(body, { ...cfg, parser: "typescript", filepath: path }));
  }
  return out;
}

const outputs = await buildOutputs();

// --- write or check -------------------------------------------------------

/** Every file under a directory, recursively (absolute paths). */
function walkFiles(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walkFiles(join(dir, e.name)) : [join(dir, e.name)],
  );
}

if (CHECK) {
  const drift = [];
  for (const [path, content] of outputs) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current === null) drift.push(`${path} (missing — run generate:icons)`);
    else if (current !== content) drift.push(`${path} (out of date — run generate:icons)`);
  }
  // Symmetric with write mode (which rm's the whole GENERATED_DIR): any committed
  // file the manifest does not produce is stale and would vanish on a real regen.
  for (const path of walkFiles(GENERATED_DIR)) {
    if (!outputs.has(path)) drift.push(`${path} (stale — not produced by the manifest)`);
  }
  if (drift.length) {
    console.error(
      `generate:icons --check FAILED — generated output is out of sync:\n  ${drift.join("\n  ")}`,
    );
    process.exit(1);
  }
  console.log(`generate:icons --check OK — ${outputs.size} files in sync.`);
} else {
  rmSync(GENERATED_DIR, { recursive: true, force: true });
  mkdirSync(UI_DIR, { recursive: true });
  for (const [path, content] of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  console.log(`generate:icons — wrote ${outputs.size} files (${resolved.length} icons).`);
}
