// scripts/generate-icons.mjs — the icon-system codegen (WP-B-4b.2).
//
// Reads the curation manifest (src/icons/manifest.json) and produces the
// committed, tree-shakeable icon surface across the three tracks (§7):
//   - ui    — codegen from lucide-react `__iconNode` (stroke idiom)
//   - ai    — codegen from lucide  +  hand-authored original art
//   - brand — codegen from simple-icons (filled marks)  +  hand-authored assets
//
// Two ownership domains:
//   MACHINE-OWNED (rm'd + rewritten every run, drift-gated):
//     src/icons/generated/<track>/<name>.tsx   one component per CODEGEN icon
//     src/icons/generated/index.ts             the tree-shakeable named-export hub
//     src/icons/generated/registry.ts          ICON_* (ui+ai) + BRAND_* (brand)
//   HUMAN-OWNED (committed, never written/removed here — only verified to exist):
//     src/icons/<track>/<name>.tsx             original art / converted brand assets
//
// The hub imports machine-owned files via "./<track>/<name>" and human-owned files
// via "../<track>/<name>". The registry follows the AC-4 split: the UI + AI tracks
// own the dynamic `<Icon name>` registry + the canonical `IconName` union; brand
// marks are named exports under their own `BrandIconName` union (NOT in the icon
// registry — logos are filled, used differently, and several names collide with UI
// icons, e.g. brand `x` vs the UI close `x`).
//
// Per-source geometry:
//   lucide          — deep-import `__iconNode`, strip the React `key` → stroke template
//   simple-icons    — read the mark's single filled `path` from icons/<slug>.svg → filled template
//   authored/asset  — NOT generated; the .tsx is hand-committed (verified to exist)
//
// ZERO runtime dependency on lucide / simple-icons — codegen is NOT runtime re-export
// (which the no-bundle rule forbids); the emitted components stand alone. Each file
// carries a provenance header citing its exact source pack + SPDX id (lucide ISC /
// simple-icons CC0-1.0) — the grounding for the net-new SPDX assertion (§12). Brand
// marks are nominative trademarks of their owners (see MARKS.md). Determinism: output
// carries no timestamp (only pinned source versions) + prettier, so committed === generated.
//
// Modes:
//   node generate-icons.mjs           — (re)generate + prettier-format + write
//   node generate-icons.mjs --check   — regenerate + format in memory, diff vs
//                                       committed; exit 1 on any drift (CI gate)

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url)); // packages/react/scripts
const PKG = dirname(HERE); // packages/react
const ICONS_DIR = join(PKG, "src", "icons");
const GENERATED_DIR = join(ICONS_DIR, "generated");
const MANIFEST_PATH = join(ICONS_DIR, "manifest.json");

const CHECK = process.argv.includes("--check");

/** Tracks whose names own the dynamic `<Icon name>` registry + the `IconName` union. */
const ICON_TRACKS = new Set(["ui", "ai"]);
/** Sources whose geometry is codegenerated (others are hand-committed .tsx). */
const CODEGEN_SOURCES = new Set(["lucide", "simple-icons"]);

/** kebab-case → PascalCase (`arrow-up-right` → `ArrowUpRight`). */
const pascal = (kebab) =>
  kebab
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

/** SVG attribute name → JSX attribute name (`stroke-width` → `strokeWidth`). */
const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// --- resolve source packs (versions + paths) -------------------------------

const lucideVersion = JSON.parse(
  readFileSync(fileURLToPath(import.meta.resolve("lucide-react/package.json")), "utf8"),
).version;

// simple-icons blocks "./package.json" in its exports map, so anchor on a stable
// mapped icon file (`./icons/*`) to locate the pack, then read package.json off disk.
const SI_ICONS_DIR = dirname(fileURLToPath(import.meta.resolve("simple-icons/icons/github.svg")));
const siVersion = JSON.parse(
  readFileSync(join(dirname(SI_ICONS_DIR), "package.json"), "utf8"),
).version;

/** Per-icon provenance header — cites the exact source pack + SPDX id (§12). */
function fileHeader(source) {
  if (source === "lucide")
    return `// AUTO-GENERATED by scripts/generate-icons.mjs from lucide-react@${lucideVersion} (ISC). Do not edit.`;
  if (source === "simple-icons")
    return `// AUTO-GENERATED by scripts/generate-icons.mjs from simple-icons@${siVersion} (CC0-1.0). Do not edit.`;
  throw new Error(`No provenance header for source "${source}".`);
}

/** Aggregate-file header (the hub + registry span all sources). */
const AGG_HEADER = `// AUTO-GENERATED by scripts/generate-icons.mjs from src/icons/manifest.json. Do not edit.`;

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
const icons = manifest.icons;

// --- resolve geometry + validate -------------------------------------------

/** Load a lucide icon's `__iconNode` (the geometry); null if the module is an alias stub. */
async function loadIconNode(name) {
  const mod = await import(`lucide-react/dist/esm/icons/${name}.mjs`);
  return mod.__iconNode ?? null;
}

/** Read an alias stub's canonical target from `export { default } from "./<canonical>.mjs"`. */
function resolveAliasTarget(aliasName) {
  const src = readFileSync(
    fileURLToPath(import.meta.resolve(`lucide-react/dist/esm/icons/${aliasName}.mjs`)),
    "utf8",
  );
  const m = src.match(/from\s+["']\.\/([a-z0-9-]+)\.mjs["']/);
  return m ? m[1] : null;
}

/** Read a simple-icons mark's single filled `path` + title from its committed SVG. */
function loadSimpleIcon(slug) {
  const file = join(SI_ICONS_DIR, `${slug}.svg`);
  if (!existsSync(file)) {
    throw new Error(
      `simple-icons@${siVersion} has no mark for slug "${slug}" (expected ${file}). ` +
        `Confirm the slug, or fall back to an owner asset and flag it (§12 — never drop silently).`,
    );
  }
  const svg = readFileSync(file, "utf8");
  const path = svg.match(/<path\s+d="([^"]+)"/)?.[1];
  if (!path) throw new Error(`simple-icons mark "${slug}" has no <path d>.`);
  const title = svg.match(/<title>([^<]*)<\/title>/)?.[1] ?? slug;
  return { path, title };
}

const seenNames = new Set();
const seenExports = new Set();
const resolved = []; // { name, track, source, codegen, importPath, exportName, aliasName, aliasExport, geometry, brand }

for (const entry of icons) {
  const { name, exportName: exportOverride, alias } = entry;
  const track = entry.track ?? "ui";
  const source = entry.source ?? "lucide";

  if (seenNames.has(name)) throw new Error(`Duplicate icon name in manifest: ${name}`);
  seenNames.add(name);

  const codegen = CODEGEN_SOURCES.has(source);
  let geometry = null; // lucide __iconNode
  let brand = null; // { path, title } for simple-icons

  if (source === "lucide") {
    // The lucide id to pull geometry FROM may differ from our canonical name
    // (e.g. `ai-sparkle` ← lucide `sparkles`).
    const lucideName = entry.lucideName ?? name;
    geometry = await loadIconNode(lucideName);
    if (geometry === null) {
      const canonical = resolveAliasTarget(lucideName);
      throw new Error(
        `Manifest "${name}" maps to lucide "${lucideName}", which is an alias stub (no __iconNode). ` +
          (canonical ? `Use lucideName "${canonical}" instead.` : "No canonical target found."),
      );
    }
  } else if (source === "simple-icons") {
    // The simple-icons slug may differ from our canonical name (e.g. `gemini` ←
    // `googlegemini`, `x-twitter` ← `x`).
    brand = loadSimpleIcon(entry.slug ?? name);
  } else if (source === "authored" || source === "asset") {
    // Hand-committed component; the generator never writes it, only verifies it
    // exists so the hub import cannot dangle.
    const file = join(ICONS_DIR, track, `${name}.tsx`);
    if (!existsSync(file)) {
      throw new Error(
        `Manifest "${name}" (source "${source}") expects a hand-authored component at ` +
          `src/icons/${track}/${name}.tsx, which is missing.`,
      );
    }
  } else {
    throw new Error(`Unknown icon source "${source}" for "${name}".`);
  }

  const exportName = exportOverride ?? pascal(name);
  if (seenExports.has(exportName)) throw new Error(`Duplicate export name: ${exportName}`);
  seenExports.add(exportName);

  // Machine-owned files sit under generated/<track>/ (imported "./<track>/<name>"
  // from the hub); human-owned files sit under src/icons/<track>/ ("../<track>/<name>").
  const importPath = codegen ? `./${track}/${name}` : `../${track}/${name}`;

  let aliasName = null;
  let aliasExport = null;
  if (alias) {
    // Exercise + validate alias resolution: the stub must point at this canonical.
    const target = resolveAliasTarget(alias);
    if (target !== name) {
      throw new Error(
        `Alias "${alias}" resolves to "${target ?? "(unknown)"}", not the declared canonical "${name}".`,
      );
    }
    aliasName = alias;
    aliasExport = pascal(alias);
    if (seenNames.has(aliasName)) throw new Error(`Alias collides with an icon name: ${aliasName}`);
    seenNames.add(aliasName);
    if (seenExports.has(aliasExport)) throw new Error(`Duplicate export name: ${aliasExport}`);
    seenExports.add(aliasExport);
  }

  resolved.push({
    name,
    track,
    source,
    codegen,
    importPath,
    exportName,
    aliasName,
    aliasExport,
    geometry,
    brand,
  });
}

// --- emit raw file bodies -------------------------------------------------

/** [tag, attrs][] → JSX children (`<circle cx="12" .../>`), React `key` stripped. */
function emitGeometry(geometry) {
  return geometry
    .map(([tag, attrs]) => {
      const parts = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${camel(k)}="${v}"`)
        .join(" ");
      return `<${tag} ${parts} />`;
    })
    .join("\n");
}

/** A codegen lucide-stroke icon component file (shared by the ui + ai tracks). */
function strokeFile({ name, exportName, geometry }) {
  return `${fileHeader("lucide")}
import { IconBase } from "../../IconBase";
import type { IconProps } from "../../icon-props";

/** \`${name}\` — generated from lucide-react@${lucideVersion} (ISC). */
export function ${exportName}(props: IconProps) {
  return (
    <IconBase {...props}>
${emitGeometry(geometry)}
    </IconBase>
  );
}
`;
}

/** A codegen simple-icons filled brand mark (`fill="currentColor"` via IconBase `filled`). */
function brandFile({ name, exportName, brand }) {
  return `${fileHeader("simple-icons")}
import { IconBase } from "../../IconBase";
import type { IconProps } from "../../icon-props";

/** \`${name}\` — the ${brand.title} mark, generated from simple-icons@${siVersion} (CC0-1.0). Nominative use only (§12, MARKS.md). */
export function ${exportName}(props: IconProps) {
  return (
    <IconBase filled {...props}>
      <path d="${brand.path}" />
    </IconBase>
  );
}
`;
}

function indexFile() {
  const lines = resolved.map((r) =>
    r.aliasExport
      ? `export { ${r.exportName}, ${r.exportName} as ${r.aliasExport} } from "${r.importPath}";`
      : `export { ${r.exportName} } from "${r.importPath}";`,
  );
  return `${AGG_HEADER}
// The tree-shakeable named-export hub: \`import { TrendingUp } from "@qball-inc/react"\`
// ships only that icon's bytes (sideEffects:false + tsup treeshake:true). Spans all
// three tracks; machine-owned files import "./<track>/<name>", hand-authored ones
// "../<track>/<name>".
${lines.join("\n")}
`;
}

/** The ICON_* block (ui + ai) — the dynamic registry + the canonical IconName union. */
function iconRegistryBlock(iconEntries) {
  const imports = iconEntries.map((r) => `import { ${r.exportName} } from "${r.importPath}";`);
  const allNames = iconEntries.flatMap((r) => (r.aliasName ? [r.name, r.aliasName] : [r.name]));
  const union = allNames.map((n) => `| "${n}"`).join("\n");
  const namesArr = allNames.map((n) => `"${n}",`).join("\n");
  const registry = iconEntries
    .flatMap((r) =>
      r.aliasName
        ? [`"${r.name}": ${r.exportName},`, `"${r.aliasName}": ${r.exportName},`]
        : [`"${r.name}": ${r.exportName},`],
    )
    .join("\n");
  return {
    imports: imports.join("\n"),
    body: `/** Every shipped icon name (canonical + aliases). A 1.0 stability contract. */
export type IconName =
${union};

/** Runtime list of every IconName — the contract surface for dynamic name use. */
export const ICON_NAMES = [
${namesArr}
] as const satisfies readonly IconName[];

/**
 * name → component for the dynamic \`<Icon name>\` registry. Intentionally retains
 * the whole set (NON-shaking); for tree-shaking use the per-icon named export.
 */
export const ICON_REGISTRY: Record<IconName, ComponentType<IconProps>> = {
${registry}
};`,
  };
}

/** The BRAND_* block — named exports under their own union (NOT in the icon registry, AC-4). */
function brandRegistryBlock(brandEntries) {
  const imports = brandEntries.map((r) => `import { ${r.exportName} } from "${r.importPath}";`);
  const union = brandEntries.map((r) => `| "${r.name}"`).join("\n");
  const namesArr = brandEntries.map((r) => `"${r.name}",`).join("\n");
  const registry = brandEntries.map((r) => `"${r.name}": ${r.exportName},`).join("\n");
  return {
    imports: imports.join("\n"),
    body: `/** Every shipped brand-mark name. Distinct from IconName (logos are not icons, AC-4). */
export type BrandIconName =
${union};

/** Runtime list of every BrandIconName. */
export const BRAND_ICON_NAMES = [
${namesArr}
] as const satisfies readonly BrandIconName[];

/** name → component for dynamic brand-mark lookup (non-shaking, like ICON_REGISTRY). */
export const BRAND_REGISTRY: Record<BrandIconName, ComponentType<IconProps>> = {
${registry}
};`,
  };
}

function registryFile() {
  const iconEntries = resolved.filter((r) => ICON_TRACKS.has(r.track));
  const brandEntries = resolved.filter((r) => r.track === "brand");

  const iconBlock = iconRegistryBlock(iconEntries);
  const brandBlock = brandEntries.length ? brandRegistryBlock(brandEntries) : null;

  const imports = [iconBlock.imports, brandBlock?.imports].filter(Boolean).join("\n");
  const bodies = [iconBlock.body, brandBlock?.body].filter(Boolean).join("\n\n");

  return `${AGG_HEADER}
import type { ComponentType } from "react";
import type { IconProps } from "../icon-props";
${imports}

${bodies}
`;
}

// --- format -------------------------------------------------------------

const prettier = await import("prettier");

/** Build the full path → prettier-formatted content map for all generated files. */
async function buildOutputs() {
  const raw = new Map();
  for (const r of resolved) {
    if (!r.codegen) continue; // hand-authored components are not (re)generated
    const body = r.source === "simple-icons" ? brandFile(r) : strokeFile(r);
    raw.set(join(GENERATED_DIR, r.track, `${r.name}.tsx`), body);
  }
  raw.set(join(GENERATED_DIR, "index.ts"), indexFile());
  raw.set(join(GENERATED_DIR, "registry.ts"), registryFile());

  const out = new Map();
  for (const [path, body] of raw) {
    const cfg = await prettier.resolveConfig(path);
    out.set(path, await prettier.format(body, { ...cfg, parser: "typescript", filepath: path }));
  }
  return out;
}

const outputs = await buildOutputs();

// --- write or check -------------------------------------------------------

/** Every file under a directory, recursively (absolute paths). */
function walkFiles(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walkFiles(join(dir, e.name)) : [join(dir, e.name)],
  );
}

if (CHECK) {
  const drift = [];
  for (const [path, content] of outputs) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current === null) drift.push(`${path} (missing — run generate:icons)`);
    else if (current !== content) drift.push(`${path} (out of date — run generate:icons)`);
  }
  // Symmetric with write mode (which rm's the whole GENERATED_DIR): any committed
  // file the manifest does not produce is stale and would vanish on a real regen.
  for (const path of walkFiles(GENERATED_DIR)) {
    if (!outputs.has(path)) drift.push(`${path} (stale — not produced by the manifest)`);
  }
  if (drift.length) {
    console.error(
      `generate:icons --check FAILED — generated output is out of sync:\n  ${drift.join("\n  ")}`,
    );
    process.exit(1);
  }
  console.log(`generate:icons --check OK — ${outputs.size} files in sync.`);
} else {
  rmSync(GENERATED_DIR, { recursive: true, force: true });
  for (const path of outputs.keys()) mkdirSync(dirname(path), { recursive: true });
  for (const [path, content] of outputs) {
    writeFileSync(path, content);
  }
  const codegenCount = resolved.filter((r) => r.codegen).length;
  console.log(`generate:icons — wrote ${outputs.size} files (${codegenCount} codegen icons).`);
}
